version: '3'

vars:
  DNS_ZONE: '{{.DNS_ZONE | default "domain.tld"}}'
  INVENTORY_FILE: '{{.INVENTORY_FILE | default "tunnels-inventory.yml"}}'
  USERS_FILE: '{{.USERS_FILE | default "tunnels-users.yml"}}'
  SSH_KEYS_PATH: '{{.SSH_KEYS_PATH | default "tunnels-ssh-keys"}}'
  SSH_KEYS_TYPE: '{{.SSH_KEYS_TYPE | default "ed25519"}}'
  SSH_LOGIN: '{{.SSH_LOGIN | default "root"}}'
  SSH_KEY: '{{.SSH_KEY | default "~/.ssh/id_ed25519"}}'
  LINK_NAME_PREFIX: '{{.LINK_NAME_PREFIX | default ""}}'
  #
  CONTAINER_NAMESPACE: '{{.CONTAINER_NAMESPACE | default "tunnels-glider"}}'
  CONTAINER_MEMORY: '{{.CONTAINER_MEMORY | default "64Mb"}}'
  #
  GLIDER_IMAGE: '{{.GLIDER_IMAGE | default "ghcr.io/nadoo/glider:0.16.4"}}'
  REPROXY_IMAGE: '{{.REPROXY_IMAGE | default "ghcr.io/umputun/reproxy:v1.2.3"}}'
  #
  SHADOWSOCK_CIPHER: '{{.SHADOWSOCK_CIPHER | default "chacha20-ietf-poly1305"}}'
  #
  NODES:
    sh: |
      yq -r -o csv \
      ".hosts[] | [ .name, .host, (.port // \"22\"), (.user // \"root\"), (.orchestrator // \"podman\"), (.tags // [] | join(\";\")), (.ssh_key // \"{{.SSH_KEY}}\") ]" \
      "{{.INVENTORY_FILE}}"
  #
  USERS:
    sh: |
      yq -r -o csv \
      ".users[] | [ .uuid, .name, (.vless_hosts // \"^\$\"), (.shadowsock_port // \"\"), (.shadowsock_pass // \"\"), (.shadowsock_hosts // \"^\$\") ]" \
      "{{.USERS_FILE}}"
  #

includes:
  podman:
    taskfile: podman.taskfile.yml
    internal: true

tasks:

  keys:
    silent: true
    cmds:
      - |
        cat << EOF
        {{$nodes := .NODES | default "" -}}
        {{$cipher := .SHADOWSOCK_CIPHER | default "" -}}
        {{$prefix := .LINK_NAME_PREFIX | default "" -}}
        {{range $_, $u := .USERS | default "" | splitLines}}
          {{if not (eq $u "") -}}
            {{$user := $u | split "," -}}
            {{$user._1 -}}
            {{$vless_hosts := $user._2 -}}
            {{$shadowsock_hosts := $user._5 -}}
            {{range $_, $n := $nodes | splitLines -}}
              {{if not (eq $n "") -}}
                {{$node := $n | split "," -}}
                {{$hostname := $node._0 -}}
                {{if not (eq $user._0 "") -}}
                  {{if (regexMatch $vless_hosts $hostname)}}
                    {{printf "vless://%s@%s:443?security=tls&type=ws&host=%s&path=/vless-%s#%s%s_vless_ws" $user._0 $node._1 $node._1 $user._0 $prefix $hostname}}
                  {{- end -}}
                {{- end -}}
                {{if not (eq $user._3 "") -}}
                  {{if (regexMatch $shadowsock_hosts $hostname)}}
                    {{printf "ss://%s@%s:%s#%s%s_shadowsocks" ((printf "%s:%s" $cipher $user._4) | b64enc) $node._1 $user._3 $prefix $hostname}}
                  {{- end -}}
                {{- end}}
              {{- end}}
            {{- end}}
          {{- end}}
        {{end}}EOF

  status:
    silent: true
    cmds:
      - for: { var: NODES, split: "\n" }
        task: 'host-podman-list:{{ (.ITEM | split ",")._0 }}'
        vars:
          HOST: '{{ (.ITEM | split ",")._1 }}'
          SSH_PORT: '{{ (.ITEM | split ",")._2 }}'
          SSH_LOGIN: '{{ (.ITEM | split ",")._3 }}'
          SSH_KEY: '{{ (.ITEM | split ",")._6 }}'
          NAMESPACE: '{{ .CONTAINER_NAMESPACE }}'

  apply:
    silent: true
    cmds:
      - for: { var: NODES, split: "\n" }
        task: 'host:{{ (.ITEM | split ",")._0 }}'
        vars:
          HOST: '{{ (.ITEM | split ",")._1 }}'
          SSH_PORT: '{{ (.ITEM | split ",")._2 }}'
          SSH_LOGIN: '{{ (.ITEM | split ",")._3 }}'
          SSH_KEY: '{{ (.ITEM | split ",")._6 }}'
          NAMESPACE: '{{ .CONTAINER_NAMESPACE }}'


  host:*:
    internal: true
    silent: true
    vars:
      HOSTNAME: '{{index .MATCH 0}}'
    cmds:
      - echo
      - task: 'host-podman-network:{{.HOSTNAME}}'
        vars:
          HOST: '{{.HOST}}'
          SSH_PORT: '{{.SSH_PORT}}'
          SSH_LOGIN: '{{.SSH_LOGIN}}'
          SSH_KEY: '{{.SSH_KEY}}'
          NAMESPACE: '{{.NAMESPACE}}'
      - task: 'host-podman-pod:{{.HOSTNAME}}'
        vars:
          HOST: '{{.HOST}}'
          SSH_PORT: '{{.SSH_PORT}}'
          SSH_LOGIN: '{{.SSH_LOGIN}}'
          SSH_KEY: '{{.SSH_KEY}}'
          NAMESPACE: '{{.NAMESPACE}}'
      - task: 'host-podman-ingress:{{.HOSTNAME}}'
        vars:
          HOST: '{{.HOST}}'
          SSH_PORT: '{{.SSH_PORT}}'
          SSH_LOGIN: '{{.SSH_LOGIN}}'
          SSH_KEY: '{{.SSH_KEY}}'
          NAMESPACE: '{{.NAMESPACE}}'
      - task: 'host-podman-prune:{{.HOSTNAME}}'
        vars:
          HOST: '{{.HOST}}'
          SSH_PORT: '{{.SSH_PORT}}'
          SSH_LOGIN: '{{.SSH_LOGIN}}'
          SSH_KEY: '{{.SSH_KEY}}'
          NAMESPACE: '{{.NAMESPACE}}'
      - task: 'host-users:{{.HOSTNAME}}'
        vars:
          HOST: '{{.HOST}}'
          SSH_PORT: '{{.SSH_PORT}}'
          SSH_LOGIN: '{{.SSH_LOGIN}}'
          SSH_KEY: '{{.SSH_KEY}}'
          NAMESPACE: '{{.NAMESPACE}}'
      - echo


  host-users:*:
    internal: true
    silent: true
    vars:
      HOSTNAME: '{{index .MATCH 0}}'
    cmds:
      - echo && echo '{{.HOSTNAME}}'
      - for: { var: USERS, split: "\n" }
        task: 'host-run:{{.HOSTNAME}}:user'
        vars:
          HOST: '{{.HOST}}'
          SSH_PORT: '{{.SSH_PORT}}'
          SSH_LOGIN: '{{.SSH_LOGIN}}'
          SSH_KEY: '{{.SSH_KEY}}'
          NAMESPACE: '{{.NAMESPACE}}'
          USER_ID: '{{ (.ITEM | split ",")._0 }}'
          USER_LOGIN: '{{ (.ITEM | split ",")._1 }}'
          VLESS_HOSTS: '{{ (.ITEM | split ",")._2 }}'
          SHADOWSOCK_PORT: '{{ (.ITEM | split ",")._3 }}'
          SHADOWSOCK_PASS: '{{ (.ITEM | split ",")._4 }}'
          SHADOWSOCK_HOSTS: '{{ (.ITEM | split ",")._5 }}'

  host-prune:*:container:*:
    internal: true
    silent: true
    vars:
      HOSTNAME: '{{index .MATCH 0}}'
      CONTAINER: '{{index .MATCH 1}}'
      PROTOCOL: '{{ .CONTAINER | splitList "-" | first }}'
      ID: '{{ slice (.CONTAINER | splitList "-") 1 | join "-" }}'
      USER:
        sh: echo "{{.USERS}}" | grep '{{.ID}}' || echo ',-,^$,,,^$,'
      HOSTS: '{{ (.USER | split ",")._2 }}|{{ (.USER | split ",")._5 }}'
    status:
      - 'grep -q -E "{{.HOSTS}}" <<< "{{.HOSTNAME}}"'
    cmds:
      - task: 'host-podman-container:{{.HOSTNAME}}:remove:{{.CONTAINER}}'
        vars:
          HOST: '{{.HOST}}'
          SSH_PORT: '{{.SSH_PORT}}'
          SSH_LOGIN: '{{.SSH_LOGIN}}'
          SSH_KEY: '{{.SSH_KEY}}'
          NAMESPACE: '{{.NAMESPACE}}'


  host-run:*:user:
    internal: true
    silent: true
    vars:
      HOSTNAME: '{{index .MATCH 0}}'
    cmds:
      - task: 'host-run:{{.HOSTNAME}}:user:vless-ws'
        vars:
          HOST: '{{.HOST}}'
          SSH_PORT: '{{.SSH_PORT}}'
          SSH_LOGIN: '{{.SSH_LOGIN}}'
          SSH_KEY: '{{.SSH_KEY}}'
          UUID: '{{.USER_ID}}'
          LOGIN: '{{.USER_LOGIN}}'
          HOSTS: '{{.VLESS_HOSTS}}'
      - task: 'host-run:{{.HOSTNAME}}:user:shadowsocks'
        vars:
          HOST: '{{.HOST}}'
          SSH_PORT: '{{.SSH_PORT}}'
          SSH_LOGIN: '{{.SSH_LOGIN}}'
          SSH_KEY: '{{.SSH_KEY}}'
          LOGIN: '{{.USER_LOGIN}}'
          PASS: '{{.SHADOWSOCK_PASS}}'
          PORT: '{{.SHADOWSOCK_PORT}}'
          HOSTS: '{{.SHADOWSOCK_HOSTS}}'

  host-run:*:user:vless-ws:
    internal: true
    silent: true
    vars:
      HOSTNAME: '{{index .MATCH 0}}'
    status:
      - 'grep -q -v -E "{{.HOSTS}}" <<< "{{.HOSTNAME}}"'
    cmds:
      - task: 'host-podman-container:{{.HOSTNAME}}:run:vless-{{.UUID}}'
        vars:
          HOST: '{{.HOST}}'
          SSH_PORT: '{{.SSH_PORT}}'
          SSH_LOGIN: '{{.SSH_LOGIN}}'
          SSH_KEY: '{{.SSH_KEY}}'
          NAMESPACE: '{{.NAMESPACE}}'
          NETWORKS: '--network ingress'
          OPTIONS: '--read-only'
          IMAGE: '{{.GLIDER_IMAGE}}'
          COMMAND: "-listen 'ws://:8080/,vless://{{.UUID}}@'"

  host-run:*:user:shadowsocks:
    internal: true
    silent: true
    vars:
      HOSTNAME: '{{index .MATCH 0}}'
    status:
      - "grep -q -v -E '{{.HOSTS}}' <<< '{{.HOSTNAME}}'"
    cmds:
      - task: 'host-podman-container:{{.HOSTNAME}}:run:{{.NAMESPACE}}-shadowsocks-{{.PORT}}'
        vars:
          HOST: '{{.HOST}}'
          SSH_PORT: '{{.SSH_PORT}}'
          SSH_LOGIN: '{{.SSH_LOGIN}}'
          SSH_KEY: '{{.SSH_KEY}}'
          NAMESPACE: '{{.NAMESPACE}}'
          OPTIONS: '--read-only'
          PORTS: '--publish {{.PORT}}:{{.PORT}}'
          COMMAND: "-listen 'ss://{{.SHADOWSOCK_CIPHER}}:{{.PASS}}@:{{.PORT}}'"


  ssh:keys:generate:
    internal: true
    silent: true
    cmds:
      - mkdir -p '{{.SSH_KEYS_PATH}}'
      - for: { var: USERS, split: "\n" }
        cmd: |
          USER_ID='{{ (.ITEM | split ",")._0 }}'
          KEY_FILE="{{.SSH_KEYS_PATH}}/${USER_ID}_ed25519"
          test -f "${KEY_FILE}" && \
            echo "Key '${USER_ID}' exists" || \
            echo ssh-keygen -t "{{.SSH_KEYS_TYPE}}" -C "" -f "${KEY_FILE}"
