#!/bin/sh

[ -f '.env' ] && eval "$(cat '.env' | sed -E 's/^(.+)/export \1/')"

if command -v go-task >/dev/null 2>&1; then
  alias task="go-task"
fi

exec task --taskfile tunnels-glider-podman.taskfile.yml --sort none ${@:-'--list-all'}
